// Icon registry — maps the string icon names used in data files
// to actual Lucide icon components. Adding a new icon here makes
// it available everywhere via <DynamicIcon name="..." />.

import type { LucideIcon } from 'lucide-react';
import {
  Zap,
  Wrench,
  HardHat,
  Users,
  GraduationCap,
  Briefcase,
  BookOpen,
  Clock,
  Gauge,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  X,
  Menu,
  Sun,
  Moon,
  Search,
  ArrowRight,
  ArrowUpRight,
  MapPin,
  Phone,
  Mail,
  Facebook,
  Instagram,
  Youtube,
  Linkedin,
  Send,
  Loader2,
  Star,
  Quote,
  Award,
  ShieldCheck,
  Lightbulb,
  Hammer,
  Scissors,
  ChefHat,
  Smartphone,
  Monitor,
  Cpu,
  Keyboard,
  Cog,
  Flame,
  Snowflake,
  RadioTower,
  Sprout,
  Egg,
  Sparkles,
  Layers,
  Construction,
  Utensils,
  HeartHandshake,
  Target,
  Eye,
  Globe,
  Info,
  ExternalLink,
  Maximize2,
  BadgeCheck,
  Timer,
  CalendarDays,
  FileText,
  ClipboardList,
  Droplets,
  Settings,
  PlayCircle,
  Building2,
  HandHeart,
  TrendingUp,
} from 'lucide-react';

export const icons: Record<string, LucideIcon> = {
  zap: Zap,
  wrench: Wrench,
  'hard-hat': HardHat,
  users: Users,
  'graduation-cap': GraduationCap,
  briefcase: Briefcase,
  'book-open': BookOpen,
  clock: Clock,
  gauge: Gauge,
  check: CheckCircle2,
  search: Search,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'map-pin': MapPin,
  phone: Phone,
  mail: Mail,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  linkedin: Linkedin,
  send: Send,
  star: Star,
  quote: Quote,
  award: Award,
  'shield-check': ShieldCheck,
  lightbulb: Lightbulb,
  hammer: Hammer,
  scissors: Scissors,
  'chef-hat': ChefHat,
  smartphone: Smartphone,
  monitor: Monitor,
  cpu: Cpu,
  keyboard: Keyboard,
  cog: Cog,
  flame: Flame,
  snowflake: Snowflake,
  radio: RadioTower,
  sprout: Sprout,
  egg: Egg,
  sparkles: Sparkles,
  layers: Layers,
  construction: Construction,
  utensils: Utensils,
  handshake: HeartHandshake,
  target: Target,
  eye: Eye,
  globe: Globe,
  info: Info,
  maximize: Maximize2,
  'badge-check': BadgeCheck,
  timer: Timer,
  calendar: CalendarDays,
  file: FileText,
  clipboard: ClipboardList,
  droplets: Droplets,
  settings: Settings,
  play: PlayCircle,
  building: Building2,
  heart: HandHeart,
  trending: TrendingUp,
};

export function getIcon(name: string): LucideIcon {
  return icons[name] ?? BookOpen;
}
