// Icon registry — maps the string icon names used in data files
// to actual Lucide icon components. Adding a new icon here makes
// it available everywhere via <DynamicIcon name="..." />.

import {
  Zap,
  Wrench,
  HardHat,
  Users,
  GraduationCap,
  Briefcase,
  BookOpen,
  Gauge,
  CheckCircle2,
  Search,
  MapPin,
  Phone,
  Mail,
  Facebook,
  Instagram,
  Youtube,
  Linkedin,
  Send,
  Star,
  Award,
  ShieldCheck,
  Lightbulb,
  Hammer,
  Scissors,
  ChefHat,
  Monitor,
  Cpu,
  Keyboard,
  Cog,
  Flame,
  Snowflake,
  RadioTower,
  Sprout,
  Egg,
  Sparkles,
  Layers,
  Construction,
  Utensils,
  HeartHandshake,
  ClipboardList,
  BadgeCheck,
  FileText,
  Droplets,
  Settings,
  Building2,
  HandHeart,
  TrendingUp,
} from 'lucide-react';

export const icons = {
  zap: Zap,
  wrench: Wrench,
  'hard-hat': HardHat,
  users: Users,
  'graduation-cap': GraduationCap,
  briefcase: Briefcase,
  'book-open': BookOpen,
  gauge: Gauge,
  check: CheckCircle2,
  search: Search,
  'map-pin': MapPin,
  phone: Phone,
  mail: Mail,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  linkedin: Linkedin,
  send: Send,
  star: Star,
  award: Award,
  'shield-check': ShieldCheck,
  lightbulb: Lightbulb,
  hammer: Hammer,
  scissors: Scissors,
  'chef-hat': ChefHat,
  monitor: Monitor,
  cpu: Cpu,
  keyboard: Keyboard,
  cog: Cog,
  flame: Flame,
  snowflake: Snowflake,
  radio: RadioTower,
  sprout: Sprout,
  egg: Egg,
  sparkles: Sparkles,
  layers: Layers,
  construction: Construction,
  utensils: Utensils,
  handshake: HeartHandshake,
  clipboard: ClipboardList,
  'badge-check': BadgeCheck,
  file: FileText,
  droplets: Droplets,
  settings: Settings,
  building: Building2,
  heart: HandHeart,
  trending: TrendingUp,
};

export function getIcon(name) {
  return icons[name] || BookOpen;
}
